version: '3.2'

services:
  database:
    image: influxdb:1.7-alpine
    restart: always
    env_file:
      - .env
    ports:
    - "8086:8086"
    volumes:
    - ./influxdb-data:/var/lib/influxdb

  app-jobrunner:
    build:
      .
    environment:
      APP_COMPONENT: jobrunner
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./btc_guru:/home/guru/btc_guru

  app-webserver:
    build:
      .
    environment:
      APP_COMPONENT: webserver
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./btc_guru:/home/guru/btc_guru
    ports:
      - "5001:5001"
