version: '3.2'

services:
  database:
    image: influxdb:1.7-alpine
    restart: always
    env_file:
      - .env
    ports:
    - "8086:8086"
    volumes:
    - ./influxdb-data:/var/lib/influxdb

  app:
    build: 
      .
    command: ./btc_guru/entrypoint.sh
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./btc_guru:/home/guru/btc_guru
      - ./historical_data:/home/guru/historical_data
